"""Download PropLine's free seven-day MLB pitcher-strikeout sample.

No API key required. Normalizes the CSV into the historical/current market schema
used by the FanDuel validation pipeline. Collection timestamps are generated by
this process so prospective tests never infer decision time from vendor fields.
"""
from pathlib import Path
from datetime import datetime, timezone
import io
import pandas as pd
import requests

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / 'data' / 'market' / 'pitcher_k_historical_raw.csv'
URL = 'https://api.prop-line.com/v1/exports/sample'


def pick(df, *names):
    for n in names:
        if n in df.columns:
            return df[n]
    return pd.Series([None] * len(df), index=df.index)


def main():
    collected_utc = pd.Timestamp(datetime.now(timezone.utc))
    collected_et = collected_utc.tz_convert('America/New_York')

    r = requests.get(URL, timeout=60)
    r.raise_for_status()
    raw = pd.read_csv(io.BytesIO(r.content), low_memory=False)
    market = pick(raw, 'market', 'market_key').astype(str)
    raw = raw[market.str.contains('pitcher_strikeouts', case=False, na=False)].copy()
    side = pick(raw, 'outcome_name', 'name', 'selection_side').astype(str).str.lower()

    commence_utc = pd.to_datetime(pick(raw, 'commence_time', 'date'), errors='coerce', utc=True)
    commence_et = commence_utc.dt.tz_convert('America/New_York')

    z = pd.DataFrame({
        'date': commence_et.dt.date,
        'commence_time_utc': commence_utc.astype('string'),
        'pitcher_name': pick(raw, 'player_name', 'description', 'player'),
        'line': pd.to_numeric(pick(raw, 'point', 'line'), errors='coerce'),
        'side': side,
        'price': pd.to_numeric(pick(raw, 'price_american', 'american_odds', 'price'), errors='coerce'),
        'sportsbook': pick(raw, 'bookmaker', 'bookmaker_title', 'sportsbook'),
        'event_id': pick(raw, 'event_id'),
        'home_team': pick(raw, 'home_team'),
        'away_team': pick(raw, 'away_team'),
        # Vendor timestamp retained for diagnostics only. Prospective timing uses
        # collected_at_* generated above.
        'vendor_snapshot_time': pick(raw, 'closing_at', 'recorded_at', 'snapshot_time'),
        'collected_at_utc': collected_utc.isoformat(),
        'collected_at_et': collected_et.isoformat(),
        # Backward-compatible field used by older scripts.
        'snapshot_time_et': collected_et.isoformat(),
        'source': 'propline_free_sample',
    })
    z = z[z.side.isin(['over', 'under'])].dropna(subset=['date', 'pitcher_name', 'line', 'price', 'sportsbook'])
    OUT.parent.mkdir(parents=True, exist_ok=True)
    z.to_csv(OUT, index=False)
    print(f'PropLine sample: {len(raw):,} pitcher-K outcome rows -> {len(z):,} normalized rows at {OUT}')
    print(f'Collected: {collected_et.isoformat()}')
    print(f'Dates: {z.date.min()} through {z.date.max()}' if len(z) else 'No usable pitcher-K rows found')


if __name__ == '__main__':
    main()
